//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_Consume_ASPNET.MyService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReservationInfo", Namespace="http://schemas.datacontract.org/2004/07/WCF_Service_RailwayReservation.ServiceMod" +
        "el")]
    [System.SerializableAttribute()]
    public partial class ReservationInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PNRNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PNRStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SuccessMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime TravelDateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PNRNumber {
            get {
                return this.PNRNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.PNRNumberField, value) != true)) {
                    this.PNRNumberField = value;
                    this.RaisePropertyChanged("PNRNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PNRStatus {
            get {
                return this.PNRStatusField;
            }
            set {
                if ((object.ReferenceEquals(this.PNRStatusField, value) != true)) {
                    this.PNRStatusField = value;
                    this.RaisePropertyChanged("PNRStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SuccessMessage {
            get {
                return this.SuccessMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.SuccessMessageField, value) != true)) {
                    this.SuccessMessageField = value;
                    this.RaisePropertyChanged("SuccessMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime TravelDate {
            get {
                return this.TravelDateField;
            }
            set {
                if ((this.TravelDateField.Equals(value) != true)) {
                    this.TravelDateField = value;
                    this.RaisePropertyChanged("TravelDate");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MyService.IPNRStatusService")]
    public interface IPNRStatusService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPNRStatusService/GetPNRStatus", ReplyAction="http://tempuri.org/IPNRStatusService/GetPNRStatusResponse")]
        WCF_Consume_ASPNET.MyService.ReservationInfo GetPNRStatus(string pnr);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPNRStatusService/GetPNRStatus", ReplyAction="http://tempuri.org/IPNRStatusService/GetPNRStatusResponse")]
        System.Threading.Tasks.Task<WCF_Consume_ASPNET.MyService.ReservationInfo> GetPNRStatusAsync(string pnr);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPNRStatusServiceChannel : WCF_Consume_ASPNET.MyService.IPNRStatusService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PNRStatusServiceClient : System.ServiceModel.ClientBase<WCF_Consume_ASPNET.MyService.IPNRStatusService>, WCF_Consume_ASPNET.MyService.IPNRStatusService {
        
        public PNRStatusServiceClient() {
        }
        
        public PNRStatusServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PNRStatusServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PNRStatusServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PNRStatusServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WCF_Consume_ASPNET.MyService.ReservationInfo GetPNRStatus(string pnr) {
            return base.Channel.GetPNRStatus(pnr);
        }
        
        public System.Threading.Tasks.Task<WCF_Consume_ASPNET.MyService.ReservationInfo> GetPNRStatusAsync(string pnr) {
            return base.Channel.GetPNRStatusAsync(pnr);
        }
    }
}
